dist: xenial # required for Python >= 3.7
language: python
python:
- 3.5
- 3.9
before_install:
- if [[ $TRAVIS_PYTHON_VERSION == "3.9" ]]; then export DO_COVERAGE=1; fi
- if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then unset DO_COVERAGE; fi
install:
- pip install -U -r requirements.txt
- if [[ $DO_COVERAGE ]]; then pip install coveralls; fi
before_script:
- ".travis/prep_regular.sh"
- if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then .travis/prep_cron.sh; fi
script:
- if ! [[ $DO_COVERAGE ]]; then python setup.py test; fi
- if [[ $DO_COVERAGE ]]; then coverage run --source=fprettify setup.py test; fi
after_success:
- if [[ $DO_COVERAGE ]]; then coveralls; fi
deploy:
  provider: pypi
  user: pseewald
  password:
    secure: eI+t+10Tzjrkt7gjiBjgTS0xyOAkw5FlUuksHiUVnbI9JDGTxKuA3J9p9JjJKK9gRnljVaqCRhv4UYTxSCTtPlxpCKEFVMHGnjr2nT6IwETTi3R5tvzZzwuReh+jO5CSb9A1hF/iys4cKl+782Bgy6YH4j2jIq60FWFLBCMQiYGza62+jF6U37C5Cmw11DxqJABW4zA1g3y1Y4VQxOXnawPH7Zp6Ag5lk/R/fpthCZo/gnYkQKbkyl7mBng5xn4t6heIGiUnYf8Tqyd46UYYHCBzo2CtR+qkzFd07dtw5Ia3uCOGxfrdaFN+Fpf8gVlMAFq/83eRDa0qSHTO1hY5mbguN1UeVB/LrQNVd82fcBfHncjsSL6/GDiu/VzCW4i7Reh4KQmalBmwReKdC/4yQ+T05OZVtu1W7FyQHJW3Z0jSvpLVttkCSD5kSWvG+pyiEpbUtUsNjr9QosbiA1JhQ+XjhdkqiJU1jZ+oP330EwDnWlD74DgJNQRIQeA2mBMeuJxG87jHwudRetXTK2GW1Idh8YWqbm7pEQ5dGLbGHm1hl0XZ2HEGbYt//fXz47wo3aWX/1wE5e4a88OS8XQ4zMN6PBGAEqRuwQo8WfhfrWGQ8NYFMRwJ0Byo0AeBBj3pYNoGj4Y45+6ETnqkFaxMGbALK+iVr2jEBTbpeOcHJYQ=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.9
